name: my first wf
on: 
    push:
    workflow_dispatch:
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4.1.7

            - name: welcome msg
              run: echo "Hello Mahmoud"

            - name: list files
              run:
                |
                chmod+x script.sh
                ./script.sh
